version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
    # Install dependencies  
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building Hotel Sales ...
      - npm run build
  
  
 

  